package com.sealight.app.bean;

import java.util.ArrayList;
import java.util.List;

/**
 * 常量类
 *
 * @author zhangjj
 * @create 2017-12-11 21:42
 **/
public class Constants {

    public static final String BASE_PATH = "D:/data/";

    /** 表格存放目录*/
    public static final String XLS_FILE_PATH = BASE_PATH + "xls/";

    public final static String ALLMAKEMAPFILE = BASE_PATH + "cache/allMakeMap.dat";

    public final static String ALLMAKEFORYEARMAP = BASE_PATH + "cache/allMakeForYearMap.dat";

    public final static String PARAMSLIST = BASE_PATH + "cache/paramsList.dat";

    public final static String PARAMSLIST_2 = BASE_PATH + "cache/paramsList_2.dat";

    public final static String LIGHTTYPELISTDATA = BASE_PATH + "cache/LightTypeListData.dat";

    /** 表格 标识 */
    public static final String FILE_SIGN = "sealightData_";


    /** 表头*/
    public static List<String> titles = new ArrayList<>();

    /** 所有灯 类型*/
    public static List<String> alLightList = new ArrayList<>();

    static{
//        titles.add("制造商");
        titles.add("型号");
        titles.add("年份");

        /**前灯 */
        alLightList.add("Fog Light Bulb Front");
        alLightList.add("Fog Light Bulb Front ((w/halogen capsule headlamps))");
        alLightList.add("Fog Light Bulb Front ((wo/projector-type headlamps))");
        alLightList.add("Fog Light Bulb Front (2.5, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Fog Light Bulb Front (Base)");
        alLightList.add("Fog Light Bulb Front (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Fog Light Bulb Front (Convertible)");
        alLightList.add("Fog Light Bulb Front (Coupe)");
        alLightList.add("Fog Light Bulb Front (Denali)");
        alLightList.add("Fog Light Bulb Front (EX)");
        alLightList.add("Fog Light Bulb Front (EX, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Fog Light Bulb Front (Early Model)");
        alLightList.add("Fog Light Bulb Front (Edge)");
        alLightList.add("Fog Light Bulb Front (FX4)");
        alLightList.add("Fog Light Bulb Front (GT)");
        alLightList.add("Fog Light Bulb Front (GTI 1.8T, with HID headlamps)");
        alLightList.add("Fog Light Bulb Front (King Ranch)");
        alLightList.add("Fog Light Bulb Front (LS)");
        alLightList.add("Fog Light Bulb Front (LT)");
        alLightList.add("Fog Light Bulb Front (LX)");
        alLightList.add("Fog Light Bulb Front (Laredo)");
        alLightList.add("Fog Light Bulb Front (Late Model)");
        alLightList.add("Fog Light Bulb Front (R-Line)");
        alLightList.add("Fog Light Bulb Front (SE)");
        alLightList.add("Fog Light Bulb Front (SLE)");
        alLightList.add("Fog Light Bulb Front (SXL)");
        alLightList.add("Fog Light Bulb Front (Sedan)");
        alLightList.add("Fog Light Bulb Front (Shelby GT500)");
        alLightList.add("Fog Light Bulb Front (Sport)");
        alLightList.add("Fog Light Bulb Front (Wagon)");
        alLightList.add("Fog Light Bulb Front (XL)");
        alLightList.add("Fog Light Bulb Front (Xtreme)");
        alLightList.add("Fog Light Bulb Front (with Adrenalin package)");
        alLightList.add("Fog Light Bulb Front (with Eyesight Package)");
        alLightList.add("Fog Light Bulb Front (with HID headlamps)");
        alLightList.add("Fog Light Bulb Front (with halogen capsule headlamps)");
        alLightList.add("Fog Light Bulb Front (with halogen infra-red headlamp)");
        alLightList.add("Fog Light Bulb Front (with out projector-type headlamps)");
        alLightList.add("Fog Light Bulb Front (with sealed beam headlamps)");
        alLightList.add("Fog Light Bulb Front (without Eyesight Package (steering responsive fog))");
        alLightList.add("Fog Light Bulb Front (without projector-type headlamps)");
        alLightList.add("Fog Light Bulb Rear");
        alLightList.add("Headlight Bulb High Beam");
        alLightList.add("Headlight Bulb High Beam ((With single projector-type headlamps))");
        alLightList.add("Headlight Bulb High Beam (Base)");
        alLightList.add("Headlight Bulb High Beam (Classic Brougham, with halogen capsule headlamps)");
        alLightList.add("Headlight Bulb High Beam (EX)");
        alLightList.add("Headlight Bulb High Beam (Early Model)");
        alLightList.add("Headlight Bulb High Beam (Eco, with halogen capsule headlamps)");
        alLightList.add("Headlight Bulb High Beam (LS)");
        alLightList.add("Headlight Bulb High Beam (S)");
        alLightList.add("Headlight Bulb High Beam (STE)");
        alLightList.add("Headlight Bulb High Beam (Sedan)");
        alLightList.add("Headlight Bulb High Beam (Supra)");
        alLightList.add("Headlight Bulb High Beam (with HID headlamps)");
        alLightList.add("Headlight Bulb High Beam (with LED headlamps)");
        alLightList.add("Headlight Bulb High Beam (with halogen capsule headlamps)");
        alLightList.add("Headlight Bulb High Beam (without LED headlamps)");
        alLightList.add("Headlight Bulb High Beam (without adaptive HID headlamps)");
        alLightList.add("Headlight Bulb High Beam (without projector-type headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam");
        alLightList.add("Headlight Bulb High Beam and Low Beam ((w/25W HID headlamps))");
        alLightList.add("Headlight Bulb High Beam and Low Beam ((w/HID headlamps))");
        alLightList.add("Headlight Bulb High Beam and Low Beam ((w/halogen capsule headlamps))");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Base)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Base, with halogen capsule headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (CE)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (CRX)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Convertible, with HID headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Coupe, with HID headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (EX, with HID headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Early Model with 2 headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Early Model)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (GTI)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Hatchback, with halogen capsule headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Late Model)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Sedan)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Veloce)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (Wagon)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (ZL1)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (with 2 round headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (with HID headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (with LED headlamps)");
        alLightList.add("Headlight Bulb High Beam and Low Beam (with halogen capsule headlamps)");
        alLightList.add("Headlight Bulb Low Beam");
        alLightList.add("Headlight Bulb Low Beam ((w/HID headlamps))");
        alLightList.add("Headlight Bulb Low Beam (Avant, with HID headlamps)");
        alLightList.add("Headlight Bulb Low Beam (Base, with HID headlamps)");
        alLightList.add("Headlight Bulb Low Beam (Coupe)");
        alLightList.add("Headlight Bulb Low Beam (GLS, with HID headlamps)");
        alLightList.add("Headlight Bulb Low Beam (Hybrid)");
        alLightList.add("Headlight Bulb Low Beam (Late Model)");
        alLightList.add("Headlight Bulb Low Beam (Limited)");
        alLightList.add("Headlight Bulb Low Beam (S, with halogen capsule headlamps)");
        alLightList.add("Headlight Bulb Low Beam (with HID headlamps)");
        alLightList.add("Headlight Bulb Low Beam (with LED headlamps)");
        alLightList.add("Headlight Bulb Low Beam (with adaptive HID headlamps)");
        alLightList.add("Headlight Bulb Low Beam (with halogen capsule headlamps)");

/**外灯 */
        alLightList.add("Back Up Light Bulb");
        alLightList.add("Back Up Light Bulb (Base)");
        alLightList.add("Back Up Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Back Up Light Bulb (Classic)");
        alLightList.add("Back Up Light Bulb (Convertible)");
        alLightList.add("Back Up Light Bulb (Coupe)");
        alLightList.add("Back Up Light Bulb (Early Model)");
        alLightList.add("Back Up Light Bulb (Sedan)");
        alLightList.add("Back Up Light Bulb (Wagon)");
        alLightList.add("Back Up Light Bulb (with LED headlamps)");
        alLightList.add("Back Up Light Bulb (with LED tail lights)");
        alLightList.add("Back Up Light Bulb (with sealed beam headlamps)");
        alLightList.add("Brake Light Bulb");
        alLightList.add("Brake Light Bulb (Adaptive)");
        alLightList.add("Brake Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Brake Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Brake Light Bulb (Cabriolet)");
        alLightList.add("Brake Light Bulb (Coupe)");
        alLightList.add("Brake Light Bulb (Coupe, Adaptive)");
        alLightList.add("Brake Light Bulb (LTZ)");
        alLightList.add("Brake Light Bulb (Late Model)");
        alLightList.add("Brake Light Bulb (With projector-type headlamps)");
        alLightList.add("Brake Light Bulb (with adjustable seat)");
        alLightList.add("Brake Light Bulb (without LED tail lights)");
        alLightList.add("Center High Mount Stop Light Bulb");
        alLightList.add("Center High Mount Stop Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Center High Mount Stop Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Center High Mount Stop Light Bulb (Bulb 3 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Center High Mount Stop Light Bulb (Coupe)");
        alLightList.add("Center High Mount Stop Light Bulb (Estate Wagon)");
        alLightList.add("Center High Mount Stop Light Bulb (Hatchback)");
        alLightList.add("Center High Mount Stop Light Bulb (Late Model)");
        alLightList.add("Center High Mount Stop Light Bulb (Sedan)");
        alLightList.add("Center High Mount Stop Light Bulb (Wagon)");
        alLightList.add("Center High Mount Stop Light Bulb (Wagon, Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Center High Mount Stop Light Bulb (with sealed beam headlamps.)");
        alLightList.add("Cornering Light Bulb");
        alLightList.add("Cornering Light Bulb (with halogen capsule headlamps)");
        alLightList.add("Daytime Running Light Bulb");
        alLightList.add("Daytime Running Light Bulb (with HID headlamps)");
        alLightList.add("Engine Compartment Light Bulb");
        alLightList.add("Engine Compartment Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Engine Compartment Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Engine Compartment Light Bulb (Demon)");
        alLightList.add("Engine Compartment Light Bulb (Swinger)");
        alLightList.add("License Plate Light Bulb");
        alLightList.add("License Plate Light Bulb (25th Anniversary Edition)");
        alLightList.add("License Plate Light Bulb (Base)");
        alLightList.add("License Plate Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("License Plate Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("License Plate Light Bulb (Clubman)");
        alLightList.add("License Plate Light Bulb (Compare to original)");
        alLightList.add("License Plate Light Bulb (Convertible)");
        alLightList.add("License Plate Light Bulb (Early Model)");
        alLightList.add("License Plate Light Bulb (Eddie Bauer)");
        alLightList.add("License Plate Light Bulb (Hatchback)");
        alLightList.add("License Plate Light Bulb (SL)");
        alLightList.add("License Plate Light Bulb (Sedan)");
        alLightList.add("License Plate Light Bulb (Sport)");
        alLightList.add("License Plate Light Bulb (with 2 headlamps)");
        alLightList.add("Parking Light Bulb");
        alLightList.add("Parking Light Bulb (Base)");
        alLightList.add("Parking Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Parking Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Parking Light Bulb (C F Sport, with halogen capsule headlamps)");
        alLightList.add("Parking Light Bulb (Early Model)");
        alLightList.add("Parking Light Bulb (Limited, Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Parking Light Bulb (With dual projector-type headlamps)");
        alLightList.add("Parking Light Bulb (with HID headlamps)");
        alLightList.add("Parking Light Bulb (with LED headlamps)");
        alLightList.add("Parking Light Bulb (with halogen capsule headlamps)");
        alLightList.add("Roof Marker Light Bulb");
        alLightList.add("Side Marker Light Bulb Front");
        alLightList.add("Side Marker Light Bulb Front (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Side Marker Light Bulb Front (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Side Marker Light Bulb Front (CS)");
        alLightList.add("Side Marker Light Bulb Front (Denali)");
        alLightList.add("Side Marker Light Bulb Front (Eco, with halogen capsule headlamps)");
        alLightList.add("Side Marker Light Bulb Front (Hatchback)");
        alLightList.add("Side Marker Light Bulb Front (LS, with halogen capsule headlamps)");
        alLightList.add("Side Marker Light Bulb Front (Swinger)");
        alLightList.add("Side Marker Light Bulb Front (With projector-type headlamps)");
        alLightList.add("Side Marker Light Bulb Front (with LED headlamps)");
        alLightList.add("Side Marker Light Bulb Front (with halogen capsule headlamps)");
        alLightList.add("Side Marker Light Bulb Rear");
        alLightList.add("Side Marker Light Bulb Rear (2 Doors)");
        alLightList.add("Side Marker Light Bulb Rear (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Side Marker Light Bulb Rear (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Side Marker Light Bulb Rear (Convertible)");
        alLightList.add("Side Marker Light Bulb Rear (Late Model)");
        alLightList.add("Side Marker Light Bulb Rear (SLE)");
        alLightList.add("Side Marker Light Bulb Rear (Sedan)");
        alLightList.add("Stepwell Light Bulb");
        alLightList.add("Tail Light Bulb");
        alLightList.add("Tail Light Bulb (Base)");
        alLightList.add("Tail Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Tail Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Tail Light Bulb (Sedan, Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Tail Light Bulb (Wagon)");
        alLightList.add("Tail Light Bulb (with fixed seat)");
        alLightList.add("Tail Light Bulb Inner");
        alLightList.add("Turn Signal Light Bulb Front");
        alLightList.add("Turn Signal Light Bulb Front ((w/HID headlamps))");
        alLightList.add("Turn Signal Light Bulb Front ((w/clear lens))");
        alLightList.add("Turn Signal Light Bulb Front ((w/halogen capsule headlamps))");
        alLightList.add("Turn Signal Light Bulb Front (2.5, with HID headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Turn Signal Light Bulb Front (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Turn Signal Light Bulb Front (Compare to original)");
        alLightList.add("Turn Signal Light Bulb Front (Coupe)");
        alLightList.add("Turn Signal Light Bulb Front (Early Model)");
        alLightList.add("Turn Signal Light Bulb Front (GTI 1.8T, with HID headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (Hatchback, with LED headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (Hatchback, with halogen capsule headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (Hybrid)");
        alLightList.add("Turn Signal Light Bulb Front (Hybrid, Sedan, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Turn Signal Light Bulb Front (LX, Sedan)");
        alLightList.add("Turn Signal Light Bulb Front (Late Model)");
        alLightList.add("Turn Signal Light Bulb Front (SR)");
        alLightList.add("Turn Signal Light Bulb Front (Sedan)");
        alLightList.add("Turn Signal Light Bulb Front (Sedan, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Turn Signal Light Bulb Front (Sedan, with HID headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (Sedan, with halogen capsule headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (Type-S)");
        alLightList.add("Turn Signal Light Bulb Front (WRX)");
        alLightList.add("Turn Signal Light Bulb Front (Wagon)");
        alLightList.add("Turn Signal Light Bulb Front (with HID headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (with LED Parking Lights)");
        alLightList.add("Turn Signal Light Bulb Front (with LED headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (with adaptive lighting)");
        alLightList.add("Turn Signal Light Bulb Front (with auto-leveling HID headlamps)");
        alLightList.add("Turn Signal Light Bulb Front (with clear lens)");
        alLightList.add("Turn Signal Light Bulb Front (with halogen capsule headlamps)");
        alLightList.add("Turn Signal Light Bulb Front Inner");
        alLightList.add("Turn Signal Light Bulb Front Outer");
        alLightList.add("Turn Signal Light Bulb Rear");
        alLightList.add("Turn Signal Light Bulb Rear (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Turn Signal Light Bulb Rear (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Turn Signal Light Bulb Rear (Early Model)");
        alLightList.add("Turn Signal Light Bulb Rear (Hatchback)");
        alLightList.add("Turn Signal Light Bulb Rear (Late Model)");
        alLightList.add("Turn Signal Light Bulb Rear (Wagon)");
        alLightList.add("Turn Signal Light Bulb Rear (location = Outer)");

/**内灯 */
        alLightList.add("Ash Tray Light Bulb");
        alLightList.add("Ash Tray Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Ash Tray Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Automatic Transmission Indicator Light Bulb");
        alLightList.add("Automatic Transmission Indicator Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Automatic Transmission Indicator Light Bulb (DL)");
        alLightList.add("Clock Light");
        alLightList.add("Courtesy Light Bulb");
        alLightList.add("Courtesy Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Courtesy Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Courtesy Light Bulb (Bulb 3 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Courtesy Light Bulb (Bulb 4 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Courtesy Light Bulb (Bulb 5 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Courtesy Light Bulb (Bulb 6 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Courtesy Light Bulb (Compare to original)");
        alLightList.add("Courtesy Light Bulb (with 2 headlamps)");
        alLightList.add("Dome Light Bulb");
        alLightList.add("Dome Light Bulb (Base, Bulb 3 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Dome Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Dome Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Dome Light Bulb (Bulb 3 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Dome Light Bulb (Convertible)");
        alLightList.add("Dome Light Bulb (Coupe)");
        alLightList.add("Dome Light Bulb (Wagon)");
        alLightList.add("Door Mirror Illumination Light Bulb");
        alLightList.add("Glove Box Light Bulb");
        alLightList.add("Glove Box Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Glove Box Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Glove Box Light Bulb (GLS)");
        alLightList.add("HVAC Temperature Control Bulb");
        alLightList.add("High Beam Indicator Light Bulb");
        alLightList.add("Ignition Light");
        alLightList.add("Instrument Panel Light Bulb");
        alLightList.add("Instrument Panel Light Bulb (4 Doors)");
        alLightList.add("Instrument Panel Light Bulb (Base, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Bulb 3 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Bulb 4 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Bulb 5 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Bulb 6 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Compare to original)");
        alLightList.add("Instrument Panel Light Bulb (Compare to original.)");
        alLightList.add("Instrument Panel Light Bulb (Convertible, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (DL, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Denali, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Estate Wagon, Bulb 4 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (LT, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Salon, Bulb 5 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (Sedan, Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Instrument Panel Light Bulb (with 2 round headlamps)");
        alLightList.add("Instrument Panel Light Bulb (with digital instrument cluster..)");
        alLightList.add("Instrument Panel Light Bulb (without digital instrument cluster)");
        alLightList.add("Instrument Panel Light Bulb (without digital instrument cluster.)");
        alLightList.add("Instrument Panel Light Bulb (without digital instrument cluster..)");
        alLightList.add("Interior Door Light Bulb");
        alLightList.add("Map Light Bulb");
        alLightList.add("Map Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Map Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Map Light Bulb (Bulb 3 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Map Light Bulb (Early Model)");
        alLightList.add("Map Light Bulb (Late Model)");
        alLightList.add("Map Light Bulb (Sedan)");
        alLightList.add("Parking Brake Indicator Light Bulb");
        alLightList.add("Radio Dial Light");
        alLightList.add("Radio Dial Light (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Radio Dial Light (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Radio Dial Light (Bulb 3 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Radio Display Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Radio Display Light Bulb (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Reading Light Bulb Rear");
        alLightList.add("Trunk or Cargo Area Light");
        alLightList.add("Trunk or Cargo Area Light (Avant)");
        alLightList.add("Trunk or Cargo Area Light (Base)");
        alLightList.add("Trunk or Cargo Area Light (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Trunk or Cargo Area Light (Bulb 2 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Trunk or Cargo Area Light (Compare to original)");
        alLightList.add("Trunk or Cargo Area Light (Coupe)");
        alLightList.add("Trunk or Cargo Area Light (Demon)");
        alLightList.add("Trunk or Cargo Area Light (Sedan)");
        alLightList.add("Trunk or Cargo Area Light (Swinger)");
        alLightList.add("Trunk or Cargo Area Light (Wagon)");
        alLightList.add("Turn Signal Indicator Light Bulb");
        alLightList.add("Turn Signal Indicator Light Bulb (Bulb 1 – Check Owner’s Manual for correct bulb)");
        alLightList.add("Turn Signal Indicator Light Bulb (Sedan)");
        alLightList.add("Vanity Mirror Light Bulb");
        alLightList.add("Vanity Mirror Light Bulb (Convertible)");
        alLightList.add("Vanity Mirror Light Bulb (Hybrid)");

        titles.addAll(alLightList);
    }
}
