package com.sealight.app;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 制造商数据
 *
 * @author zhangjj
 * @create 2017-12-10 17:05
 **/
public class MakeMapData {
    public static Map<Integer, String> allMakeMap = new HashMap<>();
    public static Map<Integer, List<Integer>> allMakeForYearMap = new HashMap<>();
    static{
        allMakeMap.put(1, "Abarth");
        allMakeMap.put(2, "AC");
        allMakeMap.put(3, "Alvis");
        allMakeMap.put(4, "Armstrong-Siddeley");
        allMakeMap.put(5, "Bentley");
        allMakeMap.put(6, "Buick");
        allMakeMap.put(7, "Cadillac");
        allMakeMap.put(8, "Chevrolet");
        allMakeMap.put(9, "Chrysler");
        allMakeMap.put(10, "Ford");
        allMakeMap.put(11, "Triumph");
        allMakeMap.put(12, "Berkeley");
        allMakeMap.put(13, "Zundapp");
        allMakeMap.put(14, "American Motors");
        allMakeMap.put(15, "Austin Healey");
        allMakeMap.put(16, "Dodge");
        allMakeMap.put(17, "Edsel");
        allMakeMap.put(18, "GMC");
        allMakeMap.put(19, "Jeep");
        allMakeMap.put(20, "Lincoln");
        allMakeMap.put(21, "Mercury");
        allMakeMap.put(22, "Oldsmobile");
        allMakeMap.put(23, "Plymouth");
        allMakeMap.put(24, "Pontiac");
        allMakeMap.put(25, "Rolls-Royce");
        allMakeMap.put(26, "Toyopet");
        allMakeMap.put(27, "Volkswagen");
        allMakeMap.put(28, "BMW");
        allMakeMap.put(29, "Amphicar");
        allMakeMap.put(30, "International");
        allMakeMap.put(31, "Apollo");
        allMakeMap.put(32, "Alpine");
        allMakeMap.put(33, "Mercedes-Benz");
        allMakeMap.put(34, "Studebaker");
        allMakeMap.put(35, "Avanti");
        allMakeMap.put(36, "Bizzarrini");
        allMakeMap.put(37, "Harley Davidson");
        allMakeMap.put(38, "Nissan");
        allMakeMap.put(39, "Porsche");
        allMakeMap.put(40, "Fiat");
        allMakeMap.put(41, "Sunbeam");
        allMakeMap.put(42, "Volvo");
        allMakeMap.put(43, "Austin");
        allMakeMap.put(44, "Renault");
        allMakeMap.put(45, "Toyota");
        allMakeMap.put(46, "Audi");
        allMakeMap.put(47, "Citroen");
        allMakeMap.put(48, "Jaguar");
        allMakeMap.put(49, "Land Rover");
        allMakeMap.put(50, "MG");
        allMakeMap.put(51, "Peugeot");
        allMakeMap.put(52, "Rover");
        allMakeMap.put(53, "Simca");
        allMakeMap.put(54, "Opel");
        allMakeMap.put(55, "Mazda");
        allMakeMap.put(56, "Honda");
        allMakeMap.put(57, "Subaru");
        allMakeMap.put(58, "Bricklin");
        allMakeMap.put(59, "Saab");
        allMakeMap.put(60, "Ski-Doo");
        allMakeMap.put(61, "Arctic Cat");
        allMakeMap.put(62, "Yamaha");
        allMakeMap.put(63, "Kawasaki");
        allMakeMap.put(64, "Suzuki");
        allMakeMap.put(65, "DeLorean");
        allMakeMap.put(66, "Isuzu");
        allMakeMap.put(67, "Lamborghini");
        allMakeMap.put(68, "Hyundai");
        allMakeMap.put(69, "Lada");
        allMakeMap.put(70, "Maserati");
        allMakeMap.put(71, "Mitsubishi");
        allMakeMap.put(72, "Polaris");
        allMakeMap.put(73, "Bertone");
        allMakeMap.put(74, "Ferrari");
        allMakeMap.put(75, "Merkur");
        allMakeMap.put(76, "Acura");
        allMakeMap.put(77, "Yugo");
        allMakeMap.put(78, "Alfa Romeo");
        allMakeMap.put(79, "Sterling");
        allMakeMap.put(80, "Daihatsu");
        allMakeMap.put(81, "Eagle");
        allMakeMap.put(82, "Geo");
        allMakeMap.put(83, "Infiniti");
        allMakeMap.put(84, "Lexus");
        allMakeMap.put(85, "Saturn");
        allMakeMap.put(86, "AM General");
        allMakeMap.put(87, "Asuna");
        allMakeMap.put(88, "Kia");
        allMakeMap.put(89, "KTM");
        allMakeMap.put(90, "Aprilia");
        allMakeMap.put(91, "Buell");
        allMakeMap.put(92, "Moto Guzzi");
        allMakeMap.put(93, "Ducati");
        allMakeMap.put(94, "Victory");
        allMakeMap.put(95, "Daewoo");
        allMakeMap.put(96, "Gas Gas");
        allMakeMap.put(97, "Vespa");
        allMakeMap.put(98, "Freightliner");
        allMakeMap.put(99, "Hummer");
        allMakeMap.put(100, "Mini");
        allMakeMap.put(101, "Maybach");
        allMakeMap.put(102, "Scion");
        allMakeMap.put(103, "Hyosung");
        allMakeMap.put(104, "Piaggio");
        allMakeMap.put(105, "Smart");
        allMakeMap.put(106, "Bugatti");
        allMakeMap.put(107, "Can-Am");
        allMakeMap.put(108, "Tesla");
        allMakeMap.put(109, "Indian");
        allMakeMap.put(110, "Aston Martin");
        allMakeMap.put(111, "Ram");
        allMakeMap.put(112, "Think");
        allMakeMap.put(113, "VPG");
        allMakeMap.put(114, "Erik Buell Racing");
        allMakeMap.put(115, "Fisker");
        allMakeMap.put(116, "ZERO");
        allMakeMap.put(117, "SRT");
        allMakeMap.put(118, "Mobility Ventures");
        allMakeMap.put(119, "Genesis");


        List<Integer> list = null;

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        allMakeForYearMap.put(1, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        allMakeForYearMap.put(2, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        allMakeForYearMap.put(3, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        allMakeForYearMap.put(4, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(5, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(6, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(7, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(8, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(9, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(10, list);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(11, list);

        list = new ArrayList<>();
        list.add(2);
        list.add(3);
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        allMakeForYearMap.put(12, list);

        list = new ArrayList<>();
        list.add(2);
        list.add(3);
        list.add(4);
        allMakeForYearMap.put(13, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        allMakeForYearMap.put(14, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        allMakeForYearMap.put(15, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(16, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        allMakeForYearMap.put(17, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(18, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(19, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(20, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        allMakeForYearMap.put(21, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        allMakeForYearMap.put(22, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        allMakeForYearMap.put(23, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        allMakeForYearMap.put(24, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(32);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(25, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        allMakeForYearMap.put(26, list);

        list = new ArrayList<>();
        list.add(4);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(27, list);

        list = new ArrayList<>();
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(28, list);

        list = new ArrayList<>();
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        allMakeForYearMap.put(29, list);

        list = new ArrayList<>();
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        allMakeForYearMap.put(30, list);

        list = new ArrayList<>();
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        allMakeForYearMap.put(31, list);

        list = new ArrayList<>();
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        allMakeForYearMap.put(32, list);

        list = new ArrayList<>();
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(33, list);

        list = new ArrayList<>();
        list.add(9);
        list.add(10);
        allMakeForYearMap.put(34, list);

        list = new ArrayList<>();
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        allMakeForYearMap.put(35, list);

        list = new ArrayList<>();
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        allMakeForYearMap.put(36, list);

        list = new ArrayList<>();
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(37, list);

        list = new ArrayList<>();
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(38, list);

        list = new ArrayList<>();
        list.add(11);
        list.add(12);
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(39, list);

        list = new ArrayList<>();
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(40, list);

        list = new ArrayList<>();
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        allMakeForYearMap.put(41, list);

        list = new ArrayList<>();
        list.add(13);
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(42, list);

        list = new ArrayList<>();
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        allMakeForYearMap.put(43, list);

        list = new ArrayList<>();
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        allMakeForYearMap.put(44, list);

        list = new ArrayList<>();
        list.add(14);
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(45, list);

        list = new ArrayList<>();
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(46, list);

        list = new ArrayList<>();
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        allMakeForYearMap.put(47, list);

        list = new ArrayList<>();
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(48, list);

        list = new ArrayList<>();
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(49, list);

        list = new ArrayList<>();
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        allMakeForYearMap.put(50, list);

        list = new ArrayList<>();
        list.add(15);
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        allMakeForYearMap.put(51, list);

        list = new ArrayList<>();
        list.add(15);
        list.add(16);
        list.add(17);
        allMakeForYearMap.put(52, list);

        list = new ArrayList<>();
        list.add(15);
        list.add(16);
        list.add(17);
        allMakeForYearMap.put(53, list);

        list = new ArrayList<>();
        list.add(16);
        list.add(17);
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        allMakeForYearMap.put(54, list);

        list = new ArrayList<>();
        list.add(18);
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(55, list);

        list = new ArrayList<>();
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(56, list);

        list = new ArrayList<>();
        list.add(19);
        list.add(20);
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(57, list);

        list = new ArrayList<>();
        list.add(20);
        list.add(21);
        list.add(22);
        allMakeForYearMap.put(58, list);

        list = new ArrayList<>();
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        allMakeForYearMap.put(59, list);

        list = new ArrayList<>();
        list.add(21);
        list.add(22);
        list.add(23);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(60, list);

        list = new ArrayList<>();
        list.add(22);
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(61, list);

        list = new ArrayList<>();
        list.add(23);
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(62, list);

        list = new ArrayList<>();
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(63, list);

        list = new ArrayList<>();
        list.add(24);
        list.add(25);
        list.add(26);
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(64, list);

        list = new ArrayList<>();
        list.add(27);
        list.add(28);
        list.add(29);
        allMakeForYearMap.put(65, list);

        list = new ArrayList<>();
        list.add(27);
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        allMakeForYearMap.put(66, list);

        list = new ArrayList<>();
        list.add(28);
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(67, list);

        list = new ArrayList<>();
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(68, list);

        list = new ArrayList<>();
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        allMakeForYearMap.put(69, list);

        list = new ArrayList<>();
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(35);
        list.add(36);
        list.add(37);
        allMakeForYearMap.put(70, list);

        list = new ArrayList<>();
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(71, list);

        list = new ArrayList<>();
        list.add(29);
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(72, list);

        list = new ArrayList<>();
        list.add(30);
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        allMakeForYearMap.put(73, list);

        list = new ArrayList<>();
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(59);
        list.add(60);
        list.add(61);
        allMakeForYearMap.put(74, list);

        list = new ArrayList<>();
        list.add(31);
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        allMakeForYearMap.put(75, list);

        list = new ArrayList<>();
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(76, list);

        list = new ArrayList<>();
        list.add(32);
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        allMakeForYearMap.put(77, list);

        list = new ArrayList<>();
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(78, list);

        list = new ArrayList<>();
        list.add(33);
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        allMakeForYearMap.put(79, list);

        list = new ArrayList<>();
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        allMakeForYearMap.put(80, list);

        list = new ArrayList<>();
        list.add(34);
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        allMakeForYearMap.put(81, list);

        list = new ArrayList<>();
        list.add(35);
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        allMakeForYearMap.put(82, list);

        list = new ArrayList<>();
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(83, list);

        list = new ArrayList<>();
        list.add(36);
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(84, list);

        list = new ArrayList<>();
        list.add(37);
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        allMakeForYearMap.put(85, list);

        list = new ArrayList<>();
        list.add(38);
        list.add(39);
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        allMakeForYearMap.put(86, list);

        list = new ArrayList<>();
        list.add(38);
        list.add(39);
        allMakeForYearMap.put(87, list);

        list = new ArrayList<>();
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(88, list);

        list = new ArrayList<>();
        list.add(40);
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(89, list);

        list = new ArrayList<>();
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(90, list);

        list = new ArrayList<>();
        list.add(41);
        list.add(42);
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        allMakeForYearMap.put(91, list);

        list = new ArrayList<>();
        list.add(41);
        list.add(42);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(92, list);

        list = new ArrayList<>();
        list.add(43);
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(93, list);

        list = new ArrayList<>();
        list.add(44);
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(94, list);

        list = new ArrayList<>();
        list.add(45);
        list.add(46);
        list.add(47);
        list.add(48);
        allMakeForYearMap.put(95, list);

        list = new ArrayList<>();
        list.add(46);
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        allMakeForYearMap.put(96, list);

        list = new ArrayList<>();
        list.add(47);
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(97, list);

        list = new ArrayList<>();
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(98, list);

        list = new ArrayList<>();
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        allMakeForYearMap.put(99, list);

        list = new ArrayList<>();
        list.add(48);
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(100, list);

        list = new ArrayList<>();
        list.add(49);
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        allMakeForYearMap.put(101, list);

        list = new ArrayList<>();
        list.add(50);
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(102, list);

        list = new ArrayList<>();
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        allMakeForYearMap.put(103, list);

        list = new ArrayList<>();
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(104, list);

        list = new ArrayList<>();
        list.add(51);
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(105, list);

        list = new ArrayList<>();
        list.add(52);
        list.add(53);
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        allMakeForYearMap.put(106, list);

        list = new ArrayList<>();
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(107, list);

        list = new ArrayList<>();
        list.add(54);
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(108, list);

        list = new ArrayList<>();
        list.add(55);
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(109, list);

        list = new ArrayList<>();
        list.add(56);
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(110, list);

        list = new ArrayList<>();
        list.add(57);
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(111, list);

        list = new ArrayList<>();
        list.add(57);
        allMakeForYearMap.put(112, list);

        list = new ArrayList<>();
        list.add(57);
        list.add(58);
        allMakeForYearMap.put(113, list);

        list = new ArrayList<>();
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(62);
        list.add(63);
        allMakeForYearMap.put(114, list);

        list = new ArrayList<>();
        list.add(58);
        allMakeForYearMap.put(115, list);

        list = new ArrayList<>();
        list.add(58);
        list.add(59);
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(116, list);

        list = new ArrayList<>();
        list.add(59);
        list.add(60);
        allMakeForYearMap.put(117, list);

        list = new ArrayList<>();
        list.add(60);
        list.add(61);
        list.add(62);
        allMakeForYearMap.put(118, list);

        list = new ArrayList<>();
        list.add(63);
        allMakeForYearMap.put(119, list);








    }
}
